import MyProfilePic from './components/MyProfilePic';
import NavBar from './components/NavBar';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Akhlaq's Blog",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} dark:bg-slate-600`}>
        <NavBar />
        <MyProfilePic />
        {children}
      </body>
    </html>
  );
}

